In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("./LR/train__Train.csv")

In [4]:
data

Applicant Id         Name as in Certficate Date of Birth           State  \
0             806             A Prasanna Jyothi    12/28/1991  Andhra Pradesh   
1             692                    A Preetha     12/11/1991          Kerala   
2             417                A Suman Bharti     12/1/1988       Jharkhand   
3             847                   A Vinay Sai       Krishna  Andhra Pradesh   
4             126              A.Dhanalakshmi       3/11/1991      Tamil Nadu   
5             798                    A.Eswari        9/4/1991      Tamil Nadu   
6            1400                A.Loganathan       8/31/1991      Tamil Nadu   
7             408                     A.Ramya       4/17/1992      Tamil Nadu   
8             742                   A.Sandhya       3/31/1992  Andhra Pradesh   
9             676                A.Saraswathi       9/17/1990      Tamil Nadu   
10            664        A.Sreevalli Kameswari       9/7/1992  Andhra Pradesh   
11            464                 Aaina Sharma      12/6/1991           Delhi   
12            265               Aakansha Arora     10/10/1991           Delhi   
13           1321             Aakash Prajapati      7/11/1991       Rajasthan   
14           1157                 Aakash Uppal       7/1/1991           Delhi   
15             52                 Aanchal Rout      1/27/1991          Odisha   
16           1353                 Aarif Shaikh     11/10/1991     Maharashtra   
17            494                  Aaysha Khan       4/3/1993  Madhya Pradesh   
18            298                      Abarna        7/5/1992      Tamil Nadu   
19           1392                     Abdhesh       12/9/1990  Madhya Pradesh   
20           1111                     Abdulla        8/6/1989      Tamil Nadu   
21            963        Abhigna Milanbhai Pota     2/11/1992         Gujarat   
22           1366               Abhijit Biswas       4/2/1991     West Bengal   
23           1352                   Abhijith T     12/25/1991          Kerala   
24            710                    Abhinaya       1/23/1992      Tamil Nadu   
25           1502               Abhisek Behera      5/21/1992          Odisha   
26           1103                 Abhisek Dash      8/26/1991          Odisha   
27           1250              Abhishek  Gaurav     1/14/1992           Bihar   
28           1281                 Abhishek Bal       8/2/1991     West Bengal   
29           1341               Abhishek Basak      9/26/1987     West Bengal   
..            ...                           ...           ...             ...   
970           291               Priyanka Arora      9/14/1992           Delhi   
971            75                 Priyanka Dey      8/17/1991     West Bengal   
972           430            Priyanka Kundekar     11/25/1991       Karnataka   
973           146              Priyanka M Kotia    12/28/1991         Gujarat   
974           398             Priyanka Minocha      7/14/1991           Delhi   
975           366                   Priyanka R      10/2/1992      Tamil Nadu   
976           535              Priyanka Sarkar      3/15/1991     West Bengal   
977           294               Priyanka Singh       9/9/1991       Rajasthan   
978           760                  Priyanka.S       6/20/1992      Tamil Nadu   
979           587         Protibha Chakravorty      6/14/1991           Delhi   
980           127                 Prti Agarwal       9/8/1991     West Bengal   
981           585                   Puja Basak       9/5/1991     West Bengal   
982           367                 Puja Chandra     12/25/1990     West Bengal   
983           949                Pulkit Gosain      5/20/1991           Delhi   
984          1280                      Puneet        9/2/1990          Punjab   
985            96                 Puneeta Bedi      4/14/1989          Punjab   
986          1175                  Punit Dabhi       3/2/1991         Gujarat   
987           678                   

In [5]:
x = data.iloc[:,5:6]
x.isnull().sum()

Weight    121
dtype: int64

In [6]:
x = x.fillna(x.mean())

In [7]:
x

Weight
0    44.000000
1    52.400000
2    57.000000
3    49.000000
4    51.000000
5    58.816382
6    54.000000
7    47.700000
8    53.000000
9    45.900000
10   38.600000
11   55.900000
12   58.816382
13   53.000000
14   53.000000
15   45.000000
16   62.000000
17   65.000000
18   58.816382
19   63.000000
20   73.000000
21   64.000000
22   53.000000
23   56.000000
24   43.700000
25   44.000000
26   55.000000
27   65.000000
28   48.000000
29   80.000000
..         ...
970  58.816382
971  60.000000
972  35.000000
973  59.000000
974  57.500000
975  50.400000
976  31.100000
977  58.816382
978  37.600000
979  57.000000
980  40.000000
981  52.900000
982  50.200000
983  65.000000
984  78.000000
985  60.000000
986  62.000000
987  58.900000
988  58.816382
989  62.000000
990  60.000000
991  64.000000
992  72.000000
993  49.000000
994  59.000000
995  65.900000
996  58.816382
997  57.000000
998  75.000000
999  54.000000

[1000 rows x 1 columns]

In [8]:
x.isnull().sum()

Weight    0
dtype: int64

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lr = LinearRegression()

In [11]:
from sklearn.model_selection import train_test_split


In [48]:
x_train1,y_train1,x_test1,y_test1 = train_test_split(x,y,test_size=.2)

(750,)

In [12]:
y=data.iloc[:,4]
y.isnull().sum()

121

In [13]:
y = y.fillna(y.mean())

In [14]:
lr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
test = pd.read_csv("./LR/test__Test.csv")
test

Applicant Id  Name as in Certficate Date of Birth             State  \
0           1496            Raman Bisen    10/22/1988    Madhya Pradesh   
1           1110     Raman Kumar Sharma     10/2/1989             Delhi   
2            560                 Ramani     7/10/1992    Andhra Pradesh   
3            617           Ramathilagam     7/20/1992        Tamil Nadu   
4            874               Ramees C      4/3/1991            Kerala   
5           1155        Ramen Mukherjee     8/14/1990       West Bengal   
6           1153                 Ramesh     2/24/1992       Maharashtra   
7           1475   Ramkrishna Bhadaniya      2/9/1990    Madhya Pradesh   
8            102              Ramya G S     7/24/1991         Karnataka   
9            534              Ramya.B.S      7/7/1992        Tamil Nadu   
10           401           Ramyashree.C     12/2/1991         Karnataka   
11          1369    Ranjeet Kumar Yadav     1/12/1993             Bihar   
12          1226  Ranjeet Singh Kushwah     5/28/1991    Madhya Pradesh   
13            14             Ranjitha.S     5/13/1991         Karnataka   
14           976              Rasheed.A     4/24/1991            Kerala   
15           625                  Rashi      8/3/1990  Himachal Pradesh   
16          1213           Rashid Kamal      5/9/1992        Tamil Nadu   
17          1297     Rashmiranjan Sahoo      6/1/1991            Odisha   
18          1367           Ratheesh G.R    12/30/1991            Kerala   
19          1058      Rathijit Adhikary      3/9/1991       West Bengal   
20          1329             Ravi Gupta     6/10/1992       Maharashtra   
21           968               Raviteja    10/22/1992    Andhra Pradesh   
22          1130               Raviteja     5/22/1991    Andhra Pradesh   

    Weight Gender  Height  
0     58.0      M     NaN  
1     70.0      M     NaN  
2     52.5      F     NaN  
3     39.8      F     NaN  
4     60.0      M     NaN  
5     79.0      M     NaN  
6     40.0      M     NaN  
7     68.0      M     NaN  
8     46.0      F     NaN  
9     57.0      F     NaN  
10    38.0      F     NaN  
11    51.0      M     NaN  
12    76.0      M     NaN  
13    55.0      F     NaN  
14    52.0      M     NaN  
15    75.0      F     NaN  
16    74.0      M     NaN  
17    67.0      M     NaN  
18    48.0      M     NaN  
19    70.0      M     NaN  
20    67.0      M     NaN  
21    85.0      M     NaN  
22    74.0      M     NaN

In [82]:
x_test = test.iloc[:,4]

In [83]:
np.array(x_test)

array([ 58. ,  70. ,  52.5,  39.8,  60. ,  79. ,  40. ,  68. ,  46. ,
        57. ,  38. ,  51. ,  76. ,  55. ,  52. ,  75. ,  74. ,  67. ,
        48. ,  70. ,  67. ,  85. ,  74. ])

In [66]:
import numpy as np
prediction = lr.predict(np.array(x_test).reshape(-1,1))

In [64]:
prediction

array([ 164.28517503,  169.46797021,  161.90972723,  156.42460233,
        165.14897422,  173.35506659,  156.51098225,  168.60417101,
        159.10237984,  163.85327543,  155.64718306,  161.26187784,
        172.0593678 ,  162.98947623,  161.69377744,  171.6274682 ,
        171.1955686 ,  168.17227141,  159.96617904,  169.46797021,
        168.17227141,  175.94646419,  171.1955686 ])

In [56]:
np.array(x_test)

array([ 58. ,  70. ,  52.5,  39.8,  60. ,  79. ,  40. ,  68. ,  46. ,
        57. ,  38. ,  51. ,  76. ,  55. ,  52. ,  75. ,  74. ,  67. ,
        48. ,  70. ,  67. ,  85. ,  74. ])

In [54]:
prediction
#test['Height'] = prediction
#test.to_csv("final_LR_height.csv",index=False)

array([ 161.69377744])

# SVM

In [30]:
from sklearn import svm

In [84]:
from sklearn import datasets

In [35]:
iris = datasets.load_iris()

In [38]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [71]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

In [68]:
dir(iris)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [72]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [87]:
iris.DESCR

'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ============

In [117]:
x = iris.data[:,1:3]

In [118]:
y = iris.target

In [119]:
from sklearn.model_selection import train_test_split

In [134]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2)

In [137]:
clf=clf.fit(x_train,y_train)

In [143]:
pred = clf.predict(x_test)

In [142]:
from sklearn.metrics import accuracy_score

In [144]:
accuracy_score(pred,y_test)

0.93333333333333335

# KNN

In [15]:
from sklearn import neighbors, datasets
import numpy as np

In [16]:
n_neighbors = 15
iris = datasets.load_iris()
x = iris.data[:, :2]
y = iris.target

In [17]:
x

array([[ 5.1,  3.5],
       [ 4.9,  3. ],
       [ 4.7,  3.2],
       [ 4.6,  3.1],
       [ 5. ,  3.6],
       [ 5.4,  3.9],
       [ 4.6,  3.4],
       [ 5. ,  3.4],
       [ 4.4,  2.9],
       [ 4.9,  3.1],
       [ 5.4,  3.7],
       [ 4.8,  3.4],
       [ 4.8,  3. ],
       [ 4.3,  3. ],
       [ 5.8,  4. ],
       [ 5.7,  4.4],
       [ 5.4,  3.9],
       [ 5.1,  3.5],
       [ 5.7,  3.8],
       [ 5.1,  3.8],
       [ 5.4,  3.4],
       [ 5.1,  3.7],
       [ 4.6,  3.6],
       [ 5.1,  3.3],
       [ 4.8,  3.4],
       [ 5. ,  3. ],
       [ 5. ,  3.4],
       [ 5.2,  3.5],
       [ 5.2,  3.4],
       [ 4.7,  3.2],
       [ 4.8,  3.1],
       [ 5.4,  3.4],
       [ 5.2,  4.1],
       [ 5.5,  4.2],
       [ 4.9,  3.1],
       [ 5. ,  3.2],
       [ 5.5,  3.5],
       [ 4.9,  3.1],
       [ 4.4,  3. ],
       [ 5.1,  3.4],
       [ 5. ,  3.5],
       [ 4.5,  2.3],
       [ 4.4,  3.2],
       [ 5. ,  3.5],
       [ 5.1,  3.8],
       [ 4.8,  3. ],
       [ 5.1,  3.8],
       [ 4.6,

In [25]:
clf = neighbors.KNeighborsClassifier(n_neighbors=5, weights='distance')
clf.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='distance')

In [26]:
clf.predict(np.array([4.7,3]).reshape(-1,2))

array([0])

In [21]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Random Forest

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
clf = RandomForestClassifier(max_depth=2, random_state=0)

In [32]:
clf = clf.fit(x,y)

In [33]:
clf.predict(np.array([4.7,3]).reshape(-1,2))

array([0])